name: Aliwaka
version: '${version}'
main: com.obcbo.aliwaka.Aliwaka
api-version: 1.16
authors: [ ObcbO ]
description: Automatic management plugin
website: https://github.com/Encinet/Aliwaka
#此为非必须依赖
#softdepend:
commands:
  aliwaka:
    aliases:
      - aw
    description: MainCommand
permissions:
  aliwaka.admin:
    description: OnlyAdmin
    default: op